services:
  postgres:
    container_name: mageVerde-api
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mageVerde-api
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: mageVerde-api-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  minio:
    container_name: mageVerde-api-storage
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_KET_ID:-minioadmin}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data

  minio-init:
    container_name: mageVerde-api-storage-init
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_KET_ID:-minioadmin}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME:-mvp-test}
    entrypoint: >-
      /bin/sh -c '
      until mc alias set local http://minio:9000 "$${MINIO_ROOT_USER}" "$${MINIO_ROOT_PASSWORD}"; do sleep 1; done;
      mc mb --ignore-existing "local/$${AWS_BUCKET_NAME}";
      mc anonymous set download "local/$${AWS_BUCKET_NAME}";
      '
